### ISSUE TITLE
modular/admin/layouts/default.vue does not work.

### ISSUE THREAD

**Issue by jericopulvera** [cknow/nuxt-modular#1]
modular/admin/layouts/default.vue does not work.

The rootFolder/layouts/defaults.vue 
is still the one applied.

even if I create a specific layout then use it in the page it still doesn't work.

**Comment by jericopulvera** [comment]
After digging through the code I found out that the layout name is different.

```
        Object.keys(files).forEach(key => {
            console.log(key)
            modular.moduleContainer.addLayout(files[key], key);
        });

      // Outputs -> admin/default
     
```

**Comment by ricardogobbosouza** [comment]
@jericopulvera 
You're right, is with `/` and not with `-`. I'll leave it configurable
I need to make some improvements and document it better.
